[package]
name = "aranya-policy-lang"
description = "The Aranya Policy Language parser"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]
buggy = { version = "0.1.0", features = ["std"] }
# `std` is required because bin/parser-explorer uses `clap` which
# requires it for arg parsing.
aranya-policy-ast = { version = "0.7.0", path = "../aranya-policy-ast", features = ["std"] }

anyhow = { workspace = true }
clap = { version = "4.4", features = ["derive"] }
markdown = { version = "=1.0.0-alpha.17" }
pest = { version = "2" }
pest_derive = { version = "2" }
serde = { workspace = true, default-features = false, features = ["derive"] }
serde_yaml = { version = "0.9" }
