[package]
name = "idam-ffi"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = ["alloc"]

# Enable allocations.
alloc = [
	"crypto/alloc",
]

# Enable `std`.
std = [
	"alloc",

	"crypto/std",
	"policy-vm/std",
	"postcard/use-std",
	"trouble/std",
]

# Enable the testing feature.
testing = []

[dependencies]
crypto = { path = "../crypto", default-features = false, features = ["alloc"] }
policy-vm = { path = "../policy-vm", features = ["derive"] }
postcard = { workspace = true, default-features = false, features = ["heapless"] }
tracing = { workspace = true }
trouble = { path = "../trouble", default-features = false, features = ["third-party"] }

[dev-dependencies]
idam-ffi = { path = ".", features = ["testing"] }

crypto = { path = "../crypto", features = ["alloc"] }

[package.metadata.docs.rs]
all-features = true

[package.metadata.cargo-all-features]
always_include_features = [
	"alloc",
	"testing",
]
