[package]
name = "idam-ffi"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = ["alloc"]

# Enable allocations.
alloc = [
	"aranya-crypto/alloc",
]

# Enable `std`.
std = [
	"alloc",

	"aranya-crypto/std",
	"policy-vm/std",
	"postcard/use-std",
]

# Enable the testing feature.
testing = []

[dependencies]
aranya-crypto = { path = "../aranya-crypto", default-features = false, features = ["alloc"] }
policy-vm = { path = "../policy-vm", features = ["derive"] }
postcard = { workspace = true, default-features = false, features = ["heapless"] }
tracing = { workspace = true }

[dev-dependencies]
idam-ffi = { path = ".", features = ["testing"] }

aranya-crypto = { path = "../aranya-crypto", features = ["alloc"] }

[package.metadata.docs.rs]
all-features = true

[package.metadata.cargo-all-features]
always_include_features = [
	"alloc",
	"testing",
]
