name: 'Setup build tools'
description: 'Action for setting up Platform build tools'
runs:
  using: "composite"
  steps:
    - name: Cache Rust
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Rustup
      uses: spideroak-inc/setup-rust@fork
    - name: List toolchains
      shell: bash
      run: rustup toolchain list
      if: ${{ matrix.os == 'self-hosted-linux-arm' }}
    - name: Show version
      shell: bash
      run: cargo --version --verbose
    - name: glibc version
      shell: bash
      run: ldd --version
      if: ${{ matrix.os == 'self-hosted-linux-arm' }}
