[package]
name = "aranya-policy-ast"
description = "The Aranya Policy Language AST"
version = "0.4.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]

[features]
default = []

# Enable `std`.
std = ["thiserror/std", "proptest?/std"]

proptest = ["dep:proptest", "dep:proptest-derive"]

[dependencies]
serde = { workspace = true, default-features = false, features = ["derive", "alloc", "rc"] }
thiserror = { workspace = true }

proptest = { workspace = true, default-features = false, features = ["alloc"], optional = true }
proptest-derive = { workspace = true, optional = true }

[package.metadata.docs.rs]
all-features = true
