[package]
name = "aranya-policy-ast"
description = "The Aranya Policy Language AST"
version = "0.4.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]

[features]
default = []

# Enable `std`.
std = ["proptest?/std", "thiserror/std"]

proptest = ["dep:proptest"]

[dependencies]
serde = { workspace = true, default-features = false, features = ["derive", "alloc", "rc"] }
thiserror = { workspace = true }

# TODO(jdygert): remove dependency on std (text regex)
proptest = { workspace = true, default-features = false, features = ["alloc", "std"], optional = true }

[package.metadata.docs.rs]
all-features = true
