[package]
name = "aranya-policy-ast"
description = "The Aranya Policy Language AST"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true


[lints]
workspace = true


[features]
default = []

# Enable `std`.
std = [
	"aranya-policy-text/std",
	"serde/std",
	"thiserror/std",
]

proptest = [
	"aranya-policy-text/proptest",
]


[dependencies]
aranya-policy-text = { version = "0.1.2", path = "../aranya-policy-text", default-features = false }

rkyv = { workspace = true, features = ["alloc"] }
serde = { workspace = true, default-features = false, features = ["alloc"] }
serde_derive = { workspace = true }
thiserror = { workspace = true, default-features = false }


[package.metadata.docs.rs]
all-features = true


[package.metadata.cargo-machete]
ignored = [
	"serde", # Used by serde_derive.
]
