allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true
allowed-wildcard-imports = ["features"]
disallowed-macros = [
    # TODO(jdygert): Disallow core::unreachable
    # { path = "core::unreachable", reason = "use aranya_buggy::bug" }
]
