[toolchain]
channel = "nightly-2023-02-13"
components = ["rustfmt", "clippy"]
targets = [
	"aarch64-unknown-linux-gnu",
	"x86_64-apple-darwin",
	"x86_64-unknown-linux-gnu",
	"armv7-unknown-linux-gnueabihf",
	"powerpc-unknown-linux-gnu",
	"wasm32-unknown-unknown", 
]
profile = "minimal"
