[package]
name = "runtime"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
buggy = { path = "../buggy", features = ["alloc"] }
# `crypto` enables `getrandom` by default.
crypto = { path = "../crypto", default-features = false, features = ["alloc", "rand_compat"] }
policy-vm = { path = "../policy-vm" }

cfg-if = { workspace = true, default-features = false, optional = true }
heapless = { workspace = true, features = ["serde"] }
libc = { workspace = true, optional = true }
memchr = { version = "2.7.2", default-features = false, optional = true }
postcard = { workspace = true, features = ["alloc"] }
serde = { workspace = true, default-features = false, features = ["derive", "alloc"] }
spin = { workspace = true, features = ["spin_mutex"] }
tracing = { workspace = true }
vec1 = { version = "1.10.1", default-features = false, features = ["serde"] }

# Used by `testing`.
policy-module = { path = "../policy-module", optional = true }
serde_json = { version = "1.0.117", default-features = false, features = ["alloc"], optional = true }

# graphviz
dot-writer = { version = "0.1.3", optional = true }
yoke = { version = "0.7.4", features = ["derive"] }

[dev-dependencies]
runtime = { path = ".", features = ["testing", "libc"] }

policy-compiler = { path = "../policy-compiler" }
policy-lang = { path = "../policy-lang" }
policy-module = { path = "../policy-module", features = ["proptest"] }
proptest = { workspace = true, default-features = true }
serde_json = { version = "1.0.117", default-features = false, features = ["alloc"] }
tempfile = "3.9.0"
test-log = { workspace = true }
tracing-subscriber = { workspace = true, default-features = true } # affects features used by test-log

[features]
default = []

# Enable `libc`.
libc = [
	"dep:cfg-if",
	"dep:libc",
	"dep:memchr",
]

std = [
	"buggy/std",
	"crypto/std",
	"libc?/std",
	"memchr?/std",
	"policy-vm/std",
	"postcard/use-std",
	"serde/std",
	"spin/std",
	"tracing/std",
	"vec1/std",
]

testing = [
	"crypto/rand_compat",
	"policy-vm/derive",

	"dep:policy-module",
	"dep:serde_json",
]

graphviz = ["dep:dot-writer"]

[package.metadata.cargo-all-features]
always_include_features = [
	"graphviz",
	"libc",
	"std",
	"testing",
]
