[package]
name = "runtime"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
buggy = { path = "../buggy", features = ["alloc"] }
# `crypto` enables `getrandom` by default.
crypto = { path = "../crypto", default-features = false, features = ["alloc"] }
device-ffi = { path = "../device-ffi" }
perspective-ffi = { path = "../perspective-ffi" }
policy-vm = { path = "../policy-vm" }
trouble = { path = "../trouble" }

heapless = { workspace = true, features = ["serde"] }
postcard = { workspace = true, features = ["alloc"] }
serde = { workspace = true, default-features = false, features = ["derive", "alloc"] }
spin = { workspace = true, features = ["spin_mutex"] }
tracing = { workspace = true }
vec1 = { version = "1.10.1", default-features = false, features = ["serde"] }

# rustix for linear storage
rustix = { workspace = true, features = ["alloc", "fs"], optional = true }

# quic syncer
quinn = { workspace = true, optional = true }
rustls = { workspace = true, default-features = false, features = ["quic"], optional = true }
thiserror = { version = "1.0", optional = true }
tokio = { workspace = true, features = ["sync"], optional = true }

# graphviz
dot-writer = { version = "0.1.3", optional = true }

[dev-dependencies]
runtime = { path = ".", features = ["quic_syncer"] }

criterion = { version = "0.5", features = ["async_tokio"] }
once_cell = "1.18.0"
policy-lang = { path = "../policy-lang" }
rand = { workspace = true, default-features = false }
rcgen = "0.11.3"
serde_yaml = { version = "0.9" }
tempfile = "3.9.0"
test-log = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { workspace = true, default-features = true } # affects features used by test-log

# quic syncer example
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
directories-next = "2"

[features]
default = []

std = [
	"buggy/std",
	"crypto/std",
	"policy-vm/std",
	"postcard/use-std",
	"rustix?/std",
	"serde/std",
	"spin/std",
	"tracing/std",
	"trouble/std",
	"vec1/std",
]

graphviz = ["dep:dot-writer"]
model = []
quic_syncer = [
	"std",

	"dep:quinn",
	"dep:rustls",
	"dep:thiserror",
	"dep:tokio",
]

[[bench]]
name = "quic_syncer"
harness = false

[package.metadata.cargo-all-features]
always_include_features = [
	"std",
	"model",
	"quic_syncer",
	"rustix",
	"graphviz",
]
