[package]
name = "runtime"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
crypto = { path = "../crypto" }
policy-vm = { path = "../policy-vm" }
heapless = { workspace = true, features = ["serde"] }
postcard = { workspace = true }
rand = { workspace = true, default-features = false}
serde = { workspace = true, default-features = false, features = ["derive", "alloc"] }
vec1 = { version = "1.10.1", default-features = false }
spin = { workspace = true }

# quic syncer
serde_yaml = { version = "0.9", optional = true }
futures = { version = "0.3.28", optional = true }
rustls = { workspace = true, default-features = false, features = ["quic"], optional = true}
tokio = { workspace = true, features = ["full"], optional = true}
tokio-util = { workspace = true, optional = true }
quinn = { workspace = true, optional = true }

[dev-dependencies]
policy-lang = { path = "../policy-lang" }
dot-writer = "0.1.3"
rcgen = "0.11.3"
once_cell = "1.18.0"

# quic syncer
serde_yaml = "0.9"
futures = "0.3.28"
rustls = { workspace = true, default-features = false, features = ["quic"] }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
quinn = { workspace = true }

# quic syncer example
anyhow = { workspace = true }
base58 = { path = "../base58" }
directories-next = "2"
clap = { version = "4", features = ["derive"] }

[features]
std = []
default = []
quic_syncer = [
    "std", 
    "dep:serde_yaml",
    "dep:futures",
    "dep:quinn", 
    "dep:tokio", 
    "dep:tokio-util", 
    "dep:rustls"
]

[[example]]
name = "quic_syncer"
required-features = ["quic_syncer"]
