[package]
name = "runtime"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
base58 = { path = "../base58" }
buggy = { path = "../buggy" }
crypto = { path = "../crypto" }
heapless = { workspace = true, features = ["serde"] }
log = { workspace = true }
policy-vm = { path = "../policy-vm" }
postcard = { workspace = true, features = ["alloc"] }
rand = { workspace = true, default-features = false}
rustix = { version = "0.38.25", optional = true, features = ["fs"] }
serde = { workspace = true, default-features = false, features = ["derive", "alloc"] }
spin = { workspace = true }
trouble = { path = "../trouble" }
vec1 = { version = "1.10.1", default-features = false, features = ["serde"] }

# quic syncer
serde_yaml = { version = "0.9", optional = true }
futures = { version = "0.3.28", optional = true }
rustls = { workspace = true, default-features = false, features = ["quic"], optional = true}
tokio = { workspace = true, features = ["full"], optional = true}
tokio-util = { workspace = true, optional = true }
quinn = { workspace = true, optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
dot-writer = "0.1.3"
once_cell = "1.18.0"
policy-lang = { path = "../policy-lang" }
rcgen = "0.11.3"
tempfile = "3.9.0"

# quic syncer
serde_yaml = "0.9"
futures = "0.3.28"
rustls = { workspace = true, default-features = false, features = ["quic"] }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
quinn = { workspace = true }

# quic syncer example
anyhow = { workspace = true }
base58 = { path = "../base58" }
directories-next = "2"
clap = { version = "4", features = ["derive"] }

[features]
std = ["buggy/std"]
default = []
quic_syncer = [
    "std",
    "dep:serde_yaml",
    "dep:futures",
    "dep:quinn",
    "dep:tokio",
    "dep:tokio-util",
    "dep:rustls"
]
model = []

[[example]]
name = "quic_syncer"
required-features = ["quic_syncer"]

[[bench]]
name = "quic_syncer"
harness = false
required-features = ["quic_syncer"]

[package.metadata.cargo-all-features]
always_include_features = [
    "std",
    "model",
    "quic_syncer",
    "rustix",
]
