[package]
name = "runtime"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
crypto = { path = "../crypto" }
heapless = { workspace = true, features = ["serde"] }
postcard = { workspace = true }
rand = { workspace = true, default-features = false}
serde = { workspace = true, default-features = false }
vec1 = { version = "1.10.1", default-features = false }

# quic syncer
serde_yaml = { version = "0.9", optional = true }
futures = { version = "0.3.28", optional = true }
rustls = { version = "0.21.8", default-features = false, features = ["quic"], optional = true}
tokio = { version = "1.28.1", features = ["full"], optional = true}
tokio-util = { version = "0.7.8", optional = true }
quinn = { version = "0.10.1", optional = true }

[dev-dependencies]
serde_yaml = "0.9"
dot-writer = "0.1.3"
rcgen = "0.11.3"
once_cell = "1.18.0"

# quic syncer
futures = "0.3.28"
rustls = { version = "0.21.8", default-features = false, features = ["quic"] }
tokio = { version = "1.28.1", features = ["full"] }
tokio-util = { version = "0.7.8" }
quinn = { version = "0.10.1" }

[features]
std = []
default = []
quic_syncer = [
    "std", 
    "dep:serde_yaml",
    "dep:futures",
    "dep:quinn", 
    "dep:tokio", 
    "dep:tokio-util", 
    "dep:rustls"
]
