[package]
name = "runtime"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
base58 = { path = "../base58" }
buggy = { path = "../buggy", features = ["alloc"] }
# `crypto` enables `getrandom` by default.
crypto = { path = "../crypto", default-features = false }
device-ffi = { path = "../device-ffi" }
heapless = { workspace = true, features = ["serde"] }
perspective-ffi = { path = "../perspective-ffi" }
policy-vm = { path = "../policy-vm" }
postcard = { workspace = true, features = ["alloc"] }
rand = { workspace = true, default-features = false }
rustix = { version = "0.38.25", optional = true, features = ["fs"] }
serde = { workspace = true, default-features = false, features = ["derive", "alloc"] }
spin = { workspace = true, features = ["spin_mutex"] }
tracing = { workspace = true }
trouble = { path = "../trouble" }
vec1 = { version = "1.10.1", default-features = false, features = ["serde"] }

# quic syncer
futures = { version = "0.3.28", optional = true }
quinn = { workspace = true, optional = true }
rustls = { workspace = true, default-features = false, features = ["quic"], optional = true }
serde_yaml = { version = "0.9", optional = true }
tokio = { workspace = true, features = ["full"], optional = true }
tokio-util = { workspace = true, optional = true }

# graphviz
dot-writer = { version = "0.1.3", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
once_cell = "1.18.0"
policy-lang = { path = "../policy-lang" }
rcgen = "0.11.3"
tempfile = "3.9.0"
test-log = { workspace = true }
tracing-subscriber = { workspace = true, default-features = true } # affects features used by test-log

# quic syncer
futures = "0.3.28"
quinn = { workspace = true }
rustls = { workspace = true, default-features = false, features = ["quic"] }
serde_yaml = "0.9"
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }

# quic syncer example
anyhow = { workspace = true }
base58 = { path = "../base58" }
clap = { version = "4", features = ["derive"] }
directories-next = "2"

[features]
default = []

std = [
	"buggy/std",
	"crypto/std",
]

graphviz = ["dep:dot-writer"]
model = []
quic_syncer = [
	"std",

	"dep:futures",
	"dep:quinn",
	"dep:rustls",
	"dep:serde_yaml",
	"dep:tokio",
	"dep:tokio-util",
]

[[example]]
name = "quic_syncer"
required-features = ["quic_syncer"]

[[bench]]
name = "quic_syncer"
harness = false
required-features = ["quic_syncer"]

[package.metadata.cargo-all-features]
always_include_features = [
	"std",
	"model",
	"quic_syncer",
	"rustix",
	"graphviz",
]
