[package]
name = "policy-module"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
aranya-crypto = { path = "../aranya-crypto", default-features = false }
policy-ast = { path = "../policy-ast" }
proptest = { workspace = true, default-features = false, features = ["std"], optional = true }
proptest-derive = { workspace = true, optional = true }
serde = { workspace = true, default-features = false, features = ["derive"] }

[features]
default = []

proptest = [
	"aranya-crypto/proptest",
	"dep:proptest",
	"dep:proptest-derive",
	"std",
]

# Enable `std`.
std = [
	"aranya-crypto/std",
	"policy-ast/std",
	"serde/std",
]

testing = []

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = [
	# used in proptest-derive expansion
	"proptest",
]
