[package]
name = "policy-module"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
crypto = { path = "../crypto", default-features = false }
policy-ast = { path = "../policy-ast" }
serde = { workspace = true, default-features = false, features = ["derive"] }
trouble = { path = "../trouble" }

[features]
default = []

# Enable `std`.
std = [
	"crypto/std",
	"policy-ast/std",
	"serde/std",
	"trouble/std",
]

[lints]
workspace = true
