//! This code is @generated by `policy-ifgen`. DO NOT EDIT.
#![allow(clippy::duplicated_attributes)]
#![allow(clippy::enum_variant_names)]
#![allow(missing_docs)]
#![allow(non_snake_case)]
#![allow(unused_imports)]
extern crate alloc;
use alloc::vec::Vec;
use aranya_policy_ifgen::{
    macros::{actions, effect, effects, value},
    BaseId, ClientError, Value, Text,
};
/// Admin policy struct.
#[value]
pub struct Admin {
    pub uid: BaseId,
    pub name: Text,
    pub role: Text,
}
/// Enum of policy effects that can occur in response to a policy action.
#[effects]
pub enum Effect {
    UserAdded(UserAdded),
}
/// UserAdded policy effect.
#[effect]
pub struct UserAdded {
    pub uid: BaseId,
    pub name: Text,
}
/// Implements all supported policy actions.
#[actions]
pub trait ActorExt {
    fn add_user(&mut self, uid: BaseId, name: Text) -> Result<(), ClientError>;
    fn delete_user(&mut self, admin: Admin, uid: BaseId) -> Result<(), ClientError>;
}
