//! This code is @generated by `policy-ifgen`. DO NOT EDIT.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(clippy::duplicated_attributes)]
#![allow(clippy::enum_variant_names)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_imports)]
extern crate alloc;
use alloc::vec::Vec;
use aranya_policy_ifgen::{
    macros::{action, actions, effect, effects, value},
    text, BaseId, ClientError, Value, Text,
};
#[derive(Debug)]
pub enum Persistent {}
#[derive(Debug)]
pub enum Ephemeral {}
/// Admin policy struct.
#[value]
pub struct Admin {
    pub uid: BaseId,
    pub name: Text,
    pub role: Text,
}
/// Enum of policy effects that can occur in response to a policy action.
#[effects]
pub enum Effect {
    UserAdded(UserAdded),
}
/// UserAdded policy effect.
#[effect]
pub struct UserAdded {
    pub uid: BaseId,
    pub name: Text,
}
#[actions(interface = Persistent)]
pub enum PersistentAction {
    add_user(add_user),
    delete_user(delete_user),
}
#[actions(interface = Ephemeral)]
pub enum EphemeralAction {}
/// add_user policy action.
#[action(interface = Persistent)]
pub struct add_user {
    pub uid: BaseId,
    pub name: Text,
}
/// delete_user policy action.
#[action(interface = Persistent)]
pub struct delete_user {
    pub admin: Admin,
    pub uid: BaseId,
}
