[package]
name = "policy-vm-explorer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]
anyhow = { workspace = true }
aranya-crypto = { path = "../aranya-crypto" }
clap = { version = "4.4", features = ["derive"] }
policy-compiler = { path = "../policy-compiler" }
policy-lang = { path = "../policy-lang" }
policy-vm = { path = "../policy-vm", features = ["std"] }

[[bin]]
name = "policy-vm-explorer"
path = "src/main.rs"
