//! This code is @generated by `policy-ifgen`. DO NOT EDIT.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(clippy::duplicated_attributes)]
#![allow(clippy::enum_variant_names)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_imports)]
extern crate alloc;
use alloc::vec::Vec;
use aranya_core::ifgen as aranya_policy_ifgen;
use aranya_policy_ifgen::{
    macros::{action, actions, effect, effects, value},
    text, BaseId, ClientError, Value, Text,
};
#[derive(Debug)]
pub enum Persistent {}
#[derive(Debug)]
pub enum Ephemeral {}
/// PublicKeys policy struct.
#[value]
pub struct PublicKeys {
    pub ident_key: Vec<u8>,
    pub sign_key: Vec<u8>,
    pub enc_key: Vec<u8>,
}
/// Enum of policy effects that can occur in response to a policy action.
#[effects]
pub enum Effect {
    CounterIncremented(CounterIncremented),
    CounterSet(CounterSet),
    CounterValue(CounterValue),
    DeviceAdded(DeviceAdded),
    Initialized(Initialized),
}
/// CounterIncremented policy effect.
#[effect]
pub struct CounterIncremented {
    pub name: i64,
    pub value: i64,
}
/// CounterSet policy effect.
#[effect]
pub struct CounterSet {
    pub name: i64,
    pub value: i64,
}
/// CounterValue policy effect.
#[effect]
pub struct CounterValue {
    pub name: i64,
    pub value: i64,
}
/// DeviceAdded policy effect.
#[effect]
pub struct DeviceAdded {
    pub device_id: BaseId,
}
/// Initialized policy effect.
#[effect]
pub struct Initialized {
    pub device_id: BaseId,
}
#[actions(interface = Persistent)]
pub enum PersistentAction {
    init(init),
    add_device(add_device),
    set_counter(set_counter),
    increment_counter(increment_counter),
}
#[actions(interface = Ephemeral)]
pub enum EphemeralAction {
    get_counter(get_counter),
}
/// init policy action.
#[action(interface = Persistent)]
pub struct init {
    pub owner_keys: PublicKeys,
    pub nonce: i64,
}
/// add_device policy action.
#[action(interface = Persistent)]
pub struct add_device {
    pub device_keys: PublicKeys,
}
/// set_counter policy action.
#[action(interface = Persistent)]
pub struct set_counter {
    pub name: i64,
    pub value: i64,
}
/// increment_counter policy action.
#[action(interface = Persistent)]
pub struct increment_counter {
    pub name: i64,
    pub amount: i64,
}
/// get_counter policy action.
#[action(interface = Ephemeral)]
pub struct get_counter {
    pub name: i64,
}
