[package]
name = "policy-vm"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]

[features]
default = []

# Enable `FfiModule` derivation.
derive = []

# Enable `std`.
std = [
	"buggy/std",
	"crypto/std",
	"policy-ast/std",
	"trouble/std",
]

[dependencies]
buggy = { path = "../buggy", features = ["alloc"] }
cfg-if = { workspace = true, default-features = false }
crypto = { path = "../crypto", default-features = false }
policy-ast = { path = "../policy-ast" }
policy-derive = { path = "../policy-derive" }
postcard = { workspace = true, features = ["alloc"] }
serde = { workspace = true, default-features = false, features = ["derive", "alloc"] }
trouble = { path = "../trouble" }

[dev-dependencies]
anyhow = { workspace = true }
crypto = { path = "../crypto", default-features = false, features = ["alloc"] }
policy-lang = { path = "../policy-lang" }
policy-vm = { path = ".", features = ["derive"] }

[[test]]
name = "tests"
path = "tests/lib.rs"

[package.metadata.docs.rs]
all-features = true
