[package]
name = "policy-vm"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]

[features]
default = []

# Enable `FfiModule` derivation.
derive = []

# Enable `std`.
std = [
	"aranya-buggy/std",
	"aranya-crypto/std",
	"policy-ast/std",
]

[dependencies]
aranya-buggy = { path = "../aranya-buggy", features = ["alloc"] }
aranya-crypto = { path = "../aranya-crypto", default-features = false }
heapless = { workspace = true }
policy-ast = { path = "../policy-ast" }
policy-derive = { path = "../policy-derive" }
policy-module = { path = "../policy-module" }
postcard = { workspace = true, features = ["alloc"] }

[dev-dependencies]
anyhow = { workspace = true }
aranya-crypto = { path = "../aranya-crypto", default-features = false, features = ["alloc"] }
ciborium = { version = "0.2" }
policy-compiler = { path = "../policy-compiler" }
policy-lang = { path = "../policy-lang" }
policy-module = { path = "../policy-module", features = ["testing"] }
policy-vm = { path = ".", features = ["derive"] }

[package.metadata.docs.rs]
all-features = true
