[package]
name = "policy-vm"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]

[features]
default = []

# Enable `FfiModule` derivation.
derive = []

# Enable `std`.
std = [
	"buggy/std",
	"crypto/std",
	"policy-ast/std",
]

[dependencies]
buggy = { path = "../buggy", features = ["alloc"] }
crypto = { path = "../crypto", default-features = false }
policy-ast = { path = "../policy-ast" }
policy-derive = { path = "../policy-derive" }
policy-module = { path = "../policy-module" }
postcard = { workspace = true, features = ["alloc"] }

[dev-dependencies]
anyhow = { workspace = true }
ciborium = { version = "0.2" }
crypto = { path = "../crypto", default-features = false, features = ["alloc"] }
policy-compiler = { path = "../policy-compiler" }
policy-lang = { path = "../policy-lang" }
policy-module = { path = "../policy-module", features = ["testing"] }
policy-vm = { path = ".", features = ["derive"] }

[package.metadata.docs.rs]
all-features = true
