[package]
name = "rtrack-derive"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[features]
default = []

# Enable some debugging.
debug = []

# Enable the Spira integration.
spira = [
	"dep:proc-macro2",
	"dep:quote",
	"dep:syn",
]

[dependencies]
log = { workspace = true }
proc-macro2 = { workspace = true, optional = true }
quote = { workspace = true, optional = true }
syn = { workspace = true, features = ["full"], optional = true }

[package.metadata.docs.rs]
all-features = true
