[package]
name = "trouble"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
std = []

[dependencies]
cfg-if = { workspace = true }

[build-dependencies]
rustc_version = "0.4.0"
