[package]
name = "policy-lang"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]
anyhow = { workspace = true }
buggy = { path = "../buggy", features = ["std"] }
cfg-if = { version = "1" }
clap = { version = "4.4", features = ["derive"] }
crypto = { path = "../crypto" }
markdown = { version = "=1.0.0-alpha.17" }
pest = { version = "2" }
pest_derive = { version = "2" }
# `std` is required because bin/parser-explorer uses `clap` which
# requires it for arg parsing.
policy-ast = { path = "../policy-ast", features = ["std"] }
serde = { workspace = true, default-features = false, features = ["derive"] }
serde_yaml = { version = "0.9" }
