[package]
name = "aranya-policy-module"
description = "The Aranya Policy module format"
version = "0.23.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
aranya-policy-ast = { version = "0.16.0", path = "../aranya-policy-ast" }

bytes = { version = "1.12.1", default-features = false }
fnv = { workspace = true, default-features = false }
indexmap = { workspace = true, default-features = false, features = ["serde"] }
rkyv = { workspace = true, features = ["alloc", "indexmap-2"] }
postcard = { workspace = true, features = ["alloc"] }
serde = { workspace = true, default-features = false, features = ["derive"] }
sha2 = { version = "0.11", default-features = false }
thiserror = { workspace = true }
zrip = { version = "0.8.5", default-features = false, features = ["alloc", "paranoid"]}

[features]
default = []

# Enable `std`.
std = [
	"aranya-policy-ast/std",
	"serde/std",
	"thiserror/std",
]

testing = []

[lints]
workspace = true
