[package]
name = "policy-derive"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[features]
default = []

[dependencies]
policy-lang = { path = "../policy-lang" }

prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["extra-traits"] }

[package.metadata.docs.rs]
all-features = true
