[package]
name = "policy-derive"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
authors.workspace = true

[license]
private.workspace = true

[lib]
proc-macro = true

[features]
default = []

# Enable some debugging.
debug = []

[dependencies]
anyhow = { version = "1" }
log = { workspace = true }
policy-lang = { path = "../policy-lang" }
prettyplease = { version = "0.2" }
proc-macro2 = { version = "1.0" }
quote = { version = "1.0" }
syn = { version = "2.0", features = ["full", "parsing", "proc-macro", "printing"] }

[package.metadata.docs.rs]
all-features = true
