[package]
name = "canary-alloc"
version = "0.1.0"
edition = "2021"

[dependencies]
base58 = { path = "../../crates/base58" }
# `crypto` enables `getrandom` by default.
crypto = { path = "../../crates/crypto", default-features = false }
# idam-ffi = { path = "../../crates/idam-ffi" }
# policy-ast = { path = "../../crates/policy-ast" }
# policy-vm = { path = "../../crates/policy-vm" }
# runtime = { path = "../../crates/runtime" }

[profile.dev]
panic = "abort"
