[package]
name = "canary-alloc"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
aranya-buggy = { path = "../../crates/aranya-buggy" }
base58 = { path = "../../crates/base58" }
# `aranya-crypto` enables `getrandom` by default.
aranya-crypto = { path = "../../crates/aranya-crypto", default-features = false }
trouble = { path = "../../crates/trouble" }
