[package]
name = "canary-alloc"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
base58 = { path = "../../crates/base58" }
buggy = { path = "../../crates/buggy" }
# `crypto` enables `getrandom` by default.
crypto = { path = "../../crates/crypto", default-features = false }
trouble = { path = "../../crates/trouble" }
