[package]
name = "aranya-policy-ifgen"
description = "Tools for generating Rust interfaces to Aranya Policies"
version = "0.11.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
serde = [
	"aranya-policy-ifgen-macro/serde",
	"dep:serde",
]

[dependencies]
aranya-policy-ifgen-macro = { version = "0.4.0", path = "../aranya-policy-ifgen-macro" }
aranya-policy-vm = { version = "0.11.0", path = "../aranya-policy-vm" }
aranya-runtime = { version = "0.11.0", path = "../aranya-runtime" }

serde = { workspace = true, optional = true }
thiserror = { workspace = true }

[dev-dependencies]
aranya-policy-ifgen-build = { path = "../aranya-policy-ifgen-build" }
aranya-policy-lang = { path = "../aranya-policy-lang" }

goldenfile = "1.6.0"
