[package]
name = "aranya-policy-derive"
description = "Proc macros for generating Aranya Policy Language FFIs"
version = "0.5.4"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[features]
default = []

[dependencies]
aranya-policy-lang = { version = "0.6.0", path = "../aranya-policy-lang" }

prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["extra-traits"] }

[package.metadata.docs.rs]
all-features = true
