[package]
name = "buggy"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []

alloc = []
std = ["alloc", "trouble/std"]

[dependencies]
cfg-if = { workspace = true }
trouble = { path = "../trouble" }
