[package]
name = "service"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]

[features]
default = []
std = []

[dependencies]

[build-dependencies]

[dev-dependencies]
