[package]
name = "aranya-policy-ifgen-build"
description = "Code generator for aranya-policy-ifgen"
version = "0.4.3"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
aranya-policy-ast = { version = "0.5.0", path = "../aranya-policy-ast" }
aranya-policy-lang = { version = "0.4.3", path = "../aranya-policy-lang" }

anyhow = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
