[package]
name = "aranya-quic-syncer"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
aranya-buggy = { version = "0.1.0", path = "../aranya-buggy", features = ["std"] }
aranya-crypto = { version = "0.2.0", path = "../aranya-crypto", features = ["std"] }
aranya-runtime = { version = "0.3.0", path = "../aranya-runtime", features = ["std"] }

heapless = { workspace = true, features = ["serde"] }
postcard = { workspace = true, features = ["alloc"] }
quinn = { workspace = true }
s2n-quic = { workspace = true }
rustls = { workspace = true, default-features = false, features = ["quic"] }
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
aranya-crypto = { path = "../aranya-crypto", features = ["std"] }

criterion = { version = "0.5", features = ["async_tokio"] }
rcgen = "0.11.3"
test-log = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { workspace = true, default-features = true }

# quic syncer example
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
directories-next = "2"

[[bench]]
name = "quic_syncer"
harness = false
