[package]
name = "rtrack"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[features]
default = []

# Enable debugging.
debug = [
	# Currently required because it logs to stderr via
	# `eprintln`.
	"std",

	"rtrack-derive/debug",
]

# Enable the Spira integration.
spira = [
	# TODO(eric): it would be nice if we could somehow make the
	# Spira integration `no_std` compatible.
	"std",

	"rtrack-derive/spira",

	"dep:anyhow",
	"dep:chrono",
	"dep:lazy_static",
	"dep:reqwest",
	"dep:rtrack-derive",
	"dep:serde_json",
	"dep:serde_repr",
]

# Enable std
std = []

[dependencies]
anyhow = { version = "1", optional = true }
chrono = { version = "0.4", optional = true, default-features = false, features = ["clock", "std", "serde"] }
lazy_static = { version = "1.4", optional = true }
log = { workspace = true, default-features = false }
reqwest = { version = "0.11", optional = true, features = ["blocking", "json"] }
rtrack-derive = { path = "../rtrack-derive", optional = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
serde_json = { version = "1", optional = true, default-features = false, features = ["alloc"] }
serde_repr = { version = "0.1", optional = true, default-features = false }

[dev-dependencies]
# This is a bit of a hack so that we run our integration tests
# with the `spira` feature.
rtrack = { path = ".", features = ["spira"] }
itoa = { version = "1.0" }

[build-dependencies]
quote = { version = "1.0" }

[[test]]
name = "tests"
path = "tests/lib.rs"

[package.metadata.docs.rs]
all-features = true
