[package]
name = "aranya-quic-channels"
description = "Peer to peer communication using QUIC with encryption protect by Aranya Policy"
version = "0.1.0"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
aranya-fast-channels = { version = "0.5.0", path = "../aranya-fast-channels", features = ["std"] }
aranya-runtime = { version = "0.5.0", path = "../aranya-runtime", features = ["std"] }
bytes = { version = "1.0" }

anyhow = { workspace = true }
heapless = { workspace = true, features = ["serde"] }
s2n-quic = { workspace = true }
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }

[dev-dependencies]
aranya-crypto = { path = "../aranya-crypto", features = ["std"] }

criterion = { version = "0.5", features = ["async_tokio"] }
rcgen = { workspace = true }
test-log = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { workspace = true, default-features = true }
