[package]
name = "model"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
aranya-crypto = { path = "../aranya-crypto", default-features = false, features = ["alloc", "fs-keystore"] }
policy-compiler = { path = "../policy-compiler" }
policy-lang = { path = "../policy-lang" }
policy-vm = { path = "../policy-vm" }
runtime = { path = "../runtime", features = ["testing"] }

[dev-dependencies]
crypto-ffi = { path = "../crypto-ffi" }
device-ffi = { path = "../device-ffi" }
envelope-ffi = { path = "../envelope-ffi" }
idam-ffi = { path = "../idam-ffi" }
perspective-ffi = { path = "../perspective-ffi" }
postcard = { workspace = true, features = ["alloc"] }
serde = { workspace = true, features = ["derive"] }
tempfile = { version = "3.8.1" }
test-log = { workspace = true }

[lints]
workspace = true
