[package]
name = "policy-ifgen"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.4", features = ["derive"] }
policy-ifgen-core = { path = "../policy-ifgen-core" }
policy-lang = { path = "../policy-lang" }
prettyplease = { workspace = true }
syn = { version = "2.0", features = ["full"] }
