[package]
name = "policy-ifgen"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
serde = ["dep:serde", "policy-ifgen-macro/serde"]

[dependencies]
policy-ifgen-macro = { path = "../policy-ifgen-macro" }
policy-vm = { path = "../policy-vm" }
runtime = { path = "../runtime" }

serde = { workspace = true, optional = true }

[dev-dependencies]
goldenfile = "1.6.0"

policy-ifgen-build = { path = "../policy-ifgen-build" }
policy-lang = { path = "../policy-lang" }
