[package]
name = "aranya-perspective-ffi"
description = "The perspective FFI for Aranya Policy"
version = "0.5.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]

[features]
default = []

# Enable allocations.
alloc = []

# Enable std.
std = []

# Enable the `testing` module.
testing = []

[dependencies]
aranya-crypto = { version = "0.4.0", path = "../aranya-crypto", default-features = false }
aranya-policy-vm = { version = "0.5.0", path = "../aranya-policy-vm", default-features = false, features = ["derive"] }

[dev-dependencies]
aranya-crypto = { path = "../aranya-crypto", features = ["getrandom"] }

[package.metadata.docs.rs]
all-features = true

[package.metadata.cargo-all-features]
always_include_features = []

skip_feature_sets = []

denylist = []
