[package]
name = "idam"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = ["alloc"]

alloc = [
	"crypto/alloc",
]
std = [
	"alloc",
	"crypto/std",
	"policy-vm/std",
	"trouble/std",
]

[dependencies]
crypto = { path = "../crypto" }
generic-array = { version = "1", default-features = false, features = ["const-default", "serde", "zeroize"] }
policy-vm = { path = "../policy-vm" }
postcard = { workspace = true, default-features = false, features = ["heapless"] }
trouble = { path = "../trouble" }
typenum = { version = "1", default-features = false }

[dev-dependencies]
anyhow = { workspace = true }

[package.metadata.docs.rs]
all-features = true

[package.metadata.cargo-all-features]
always_include_features = [
	"alloc",
]
