[package]
name = "envelope-ffi"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = [
	"alloc",
]

# Enable allocations.
alloc = []

# Enable std.
std = [
	"alloc",

	"crypto/std",
	"policy-vm/std",
	"trouble/std",
]

[dependencies]
crypto = { path = "../crypto", default-features = false, features = ["alloc"] }
policy-vm = { path = "../policy-vm", default-features = false, features = ["derive"] }
tracing = { workspace = true }
trouble = { path = "../trouble", default-features = false }

[dev-dependencies]
crypto = { path = "../crypto", features = ["alloc", "getrandom"] }

[package.metadata.docs.rs]
all-features = true

[package.metadata.cargo-all-features]
always_include_features = [
	"alloc",
]

skip_feature_sets = []

denylist = []
