[package]
name = "aranya-policy-vm-explorer"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]
aranya-crypto = { version = "0.1.0", path = "../aranya-crypto" }
aranya-policy-compiler = { version = "0.1.0", path = "../aranya-policy-compiler" }
aranya-policy-lang = { version = "0.1.0", path = "../aranya-policy-lang" }
aranya-policy-vm = { version = "0.1.0", path = "../aranya-policy-vm", features = ["std"] }

anyhow = { workspace = true }
clap = { version = "4.4", features = ["derive"] }

[[bin]]
name = "aranya-policy-vm-explorer"
path = "src/main.rs"
