name: "Build"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string

env:
  REV: ${{ github.run_id }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.workflow }}
  cancel-in-progress: true

jobs:
  build-release:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu2404-arm64-4core
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build code
        run: cargo make build-code

      - name: Verify build didn't change any checked-in files
        run: cargo make git-unchanged
