name: "Build"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string
    secrets:
      CC_BUILD_TOKEN:
        required: true

env:
  REV: ${{ github.run_id }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.workflow }}
  cancel-in-progress: true

jobs:
  build-release:
    strategy:
      matrix:
        target:
          [
            { os: "macos-latest", suffix: "darwin-amd64" },
            { os: "self-hosted-linux-arm", suffix: "linux-arm" },
            { os: "self-hosted-linux-arm64", suffix: "linux-arm64" },
            { os: "ubuntu-latest", suffix: "linux-amd64" },
          ]
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Clean temp files
        run: rm -rf ${{ github.workspace }}/_temp
        if: ${{ matrix.os == 'self-hosted-linux-arm' }}
      - uses: ./.github/actions/setup
        with:
          gh-token: ${{ secrets.CC_BUILD_TOKEN }}
          os: ${{ matrix.target.os }}
          target: ${{ matrix.target.suffix }}

      - name: Build code
        run: cargo --verbose build-all-features --release
