name: "Correctness checks and linting"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string
    secrets:
      CC_BUILD_TOKEN:
        required: true
      GH_DOTCOM_TOKEN:
        required: true

env:
  REV: ${{ github.run_id }}
  RUSTFLAGS: -Dwarnings

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.workflow }}
  cancel-in-progress: true

jobs:
  check-fmt:
    strategy:
      matrix:
        runner: ["self-hosted-linux-amd64"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup
        with:
          ghe-token: ${{ secrets.CC_BUILD_TOKEN }}
          gh-token: ${{ secrets.GH_DOTCOM_TOKEN }}
          runner: ${{ matrix.runner }}

      - name: Check formatting
        run: cargo make check-fmt

  lint-code:
    strategy:
      matrix:
        runner:
          # TODO(eric): re-enable after we get macOS runners.
          # - "macos-latest"
          - "self-hosted-linux-arm"
          - "self-hosted-linux-arm64"
          - "self-hosted-linux-amd64"
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          ghe-token: ${{ secrets.CC_BUILD_TOKEN }}
          gh-token: ${{ secrets.GH_DOTCOM_TOKEN }}
          runner: ${{ matrix.runner }}

      - name: Check Features
        run: cargo make check-features

      - name: Run clippy test
        run: cargo make clippy

      - name: Check Canaries
        run: cargo make check-canaries
