name: "Correctness checks and linting"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string
    secrets:
      CC_BUILD_TOKEN:
        required: true
      GH_DOTCOM_TOKEN:
        required: true

env:
  REV: ${{ github.run_id }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.workflow }}
  cancel-in-progress: true

jobs:
  check-fmt:
    runs-on: "self-hosted-linux-amd64"
    steps:
      # Our runners don't get wiped between runs :/
      - name: nuke old .gitconfig
        run: rm ~/.gitconfig || true
      - uses: actions/checkout@v3
      - name: Clean temp files
        run: rm -rf ${{ github.workspace }}/_temp
        if: ${{ matrix.os == 'self-hosted-linux-arm' }}
      - uses: ./.github/actions/setup
        with:
          ghe-token: ${{ secrets.CC_BUILD_TOKEN }}
          gh-token: ${{ secrets.GH_DOTCOM_TOKEN }}
          os: ${{ matrix.os }}
      - name: Install nightly
        run: rustup toolchain install nightly
      - name: Check formatting
        run: cargo +nightly fmt --all -- --check

  lint-code:
    strategy:
      matrix:
        os:
          [
            # TODO(eric): re-enable after we get macOS runners.
            # "macos-latest",
            "self-hosted-linux-arm",
            "self-hosted-linux-arm64",
            "self-hosted-linux-amd64",
          ]
    runs-on: ${{ matrix.os }}
    steps:
      # Our runners don't get wiped between runs :/
      - name: nuke old .gitconfig
        run: rm ~/.gitconfig || true
      - uses: actions/checkout@v3
      - name: Clean temp files
        run: rm -rf ${{ github.workspace }}/_temp
        if: ${{ matrix.os == 'self-hosted-linux-arm' }}
      - uses: ./.github/actions/setup
        with:
          ghe-token: ${{ secrets.CC_BUILD_TOKEN }}
          gh-token: ${{ secrets.GH_DOTCOM_TOKEN }}
          os: ${{ matrix.os }}
      - name: Check code
        run: cargo check-all-features
      - name: Clippy
        # Set the working directory to run the clippy script
        working-directory: crates
        # Run clippy with default features, no default features, and for tests
        run: bash ../.github/scripts/clippy.sh
      - name: Check no_std compatibility
        run: cargo check
        working-directory: canaries/canary-std
      - name: Check no_alloc compatibility
        run: cargo check
        working-directory: canaries/canary-alloc
