name: "Correctness checks and linting"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string
    secrets:
      CC_BUILD_TOKEN:
        required: true
      GH_DOTCOM_TOKEN:
        required: true

env:
  REV: ${{ github.run_id }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.workflow }}
  cancel-in-progress: true

jobs:
  fmt:
    strategy:
      matrix:
        runner: ["ubuntu-latest"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Check formatting
        run: cargo make check-fmt

  canaries:
    strategy:
      matrix:
        runner: ["ubuntu-latest"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Check canaries (no-std/no-alloc)
        run: cargo make check-canaries

  clippy:
    strategy:
      matrix:
        runner: ["ubuntu-latest"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Run clippy
        run: cargo make clippy

  machete:
    strategy:
      matrix:
        runner: ["ubuntu-latest"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Check dependency usage
        run: cargo make machete

  check:
    strategy:
      matrix:
        runner: ["ubuntu-latest"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Check Features
        run: cargo make check-features
