name: "Verify aranya-embedded repo builds"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string

permissions:
  contents: read

env:
  REV: ${{ github.run_id }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.workflow }}
  cancel-in-progress: true

jobs:
  build-embedded:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout aranya-embedded repo
        uses: actions/checkout@v4
        with:
            path: aranya-core

      - name: Checkout aranya-embedded repo
        uses: actions/checkout@v4
        with:
            repository: aranya-project/aranya-embedded
            path: aranya-embedded

      - name: Install esp toolchain
        run: |
            sudo apt-get update
            sudo apt-get install libudev-dev --fix-missing
            cargo install espup --locked
            espup install
            . /home/runner/export-esp.sh
            cargo install espflash@^3 --locked

      - name: Build code
        run: |
            . /home/runner/export-esp.sh
            echo "paths = [\"/home/runner/aranya-core/aranya-core\"]" > /home/runner/aranya-core/aranya-embedded/.cargo/config.toml
            cd aranya-embedded/crates/chat-app
            cargo build
