name: "Test And Build Platform"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  REV: ${{ github.run_id }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    strategy:
      matrix:
        os: [
          "ubuntu-latest", 
          "macos-latest", 
          "windows-latest", 
          "self-hosted-linux-arm"
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Show toolchains
        run: rustup show
      - name: Show version
        run: cargo --version --verbose
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Check code
        run: cargo check --features std
      - name: Unit Tests std
        run: cargo test --features std --verbose
        # TODO: test with no_std pending
        # https://github.com/rust-lang/rust/issues/48665
        
  build-release:
    strategy:
      matrix:
        os: [
          "ubuntu-latest", 
          "macos-latest", 
          "windows-latest", 
          "self-hosted-linux-arm"
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Show toolchains
        run: rustup show
      - name: Show version
        run: cargo --version --verbose
      - name: Build code
        run: cargo build --verbose --release --features std
