name: "Publish Release Artifacts On Tag Creation"

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: release
        uses: aranya-project/release-action@main
        with:
          allowUpdates: true
          prerelease: false
          makeLatest: legacy
    outputs:
      upload-url: ${{ steps.release.outputs.upload_url }}

  build:
    uses: ./.github/workflows/doc.yml
    with:
      workflow: doc

  publish-docs:
    permissions:
      contents: write
    needs:
      - release
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download doc artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs
      - name: List files
        run: ls -R -al
      - name: Upload docs to tagged release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.upload-url }}
          asset_path: docs/docs.zip
          asset_name: docs/docs.zip
          asset_content_type: application/zip
