name: "Unit tests"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:
    inputs:
      workflow:
        required: true
        type: string
    secrets:
      CC_BUILD_TOKEN:
        required: true
      GH_DOTCOM_TOKEN:
        required: true

env:
  REV: ${{ github.run_id }}
  RUSTFLAGS: -Dwarnings

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.workflow }}
  cancel-in-progress: true

jobs:
  unit-tests:
    strategy:
      matrix:
        os:
          [
            # TODO(eric): re-enable after we get macOS runners.
            # "macos-latest",
            "self-hosted-linux-arm",
            "self-hosted-linux-arm64",
            "self-hosted-linux-amd64",
          ]
    runs-on: ${{ matrix.os }}
    steps:
      # Our runners don't get wiped between runs :/
      - name: nuke old .gitconfig
        run: rm ~/.gitconfig || true
      - uses: actions/checkout@v3
      - name: Clean temp files
        run: rm -rf ${{ github.workspace }}/_temp
        if: ${{ matrix.os == 'self-hosted-linux-arm' }}
      - uses: ./.github/actions/setup
        with:
          ghe-token: ${{ secrets.CC_BUILD_TOKEN }}
          gh-token: ${{ secrets.GH_DOTCOM_TOKEN }}
          os: ${{ matrix.os }}
      - name: Unit Tests
        run: cargo test-all-features
