[target.'cfg(target_os = "macos")']
rustflags = ["-Clink-arg=-Wl,-U,_OS_hardware_rand"]

[target.powerpc-wrs-vxworks]
rustflags = [
    "-Ctarget-cpu=e500",
    "-Crelocation-model=static",
    "-Ctarget-feature=-crt-static",
    "-Zdwarf-version=2",
]
